SELECT 
    DATE_FORMAT(S.SALES_DATE, '%Y-%m-%d') AS 'SALES_DATE',
    S.PRODUCT_ID,
    S.USER_ID,
    S.SALES_AMOUNT
FROM (
    SELECT PRODUCT_ID, USER_ID, SALES_AMOUNT, SALES_DATE FROM ONLINE_SALE
    UNION ALL
    SELECT PRODUCT_ID, NULL, SALES_AMOUNT, SALES_DATE FROM OFFLINE_SALE
) S
WHERE DATE_FORMAT(S.SALES_DATE, '%Y-%m') = '2022-03'
ORDER BY 1, 2, 3