-- MySQL
# Solution 1
SELECT COUNT(USER_ID) AS 'USERS'
FROM USER_INFO
WHERE SUBSTR(JOINED, 1, 4) = 2021 AND AGE >= 20 AND AGE <= 29

# Solution 2
SELECT COUNT(USER_ID) AS 'USERS'
FROM USER_INFO
WHERE YEAR(JOINED) = 2021 AND AGE >= 20 AND AGE <= 29

-- Oracle
SELECT COUNT(USER_ID) AS USERS
FROM USER_INFO
WHERE TO_CHAR(JOINED, 'YYYY') = '2021' AND AGE >= 20 AND AGE <= 29