SELECT 
    B.TITLE, B.BOARD_ID, P.REPLY_ID, P.WRITER_ID, P.CONTENTS,
    TO_CHAR(P.CREATED_DATE, 'YYYY-MM-DD') CREATED_DATE
FROM USED_GOODS_BOARD B, USED_GOODS_REPLY P
WHERE B.BOARD_ID = P.BOARD_ID
AND TO_CHAR(B.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY P.CREATED_DATE, B.TITLE;