SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS 'REVIEW_DATE'
FROM MEMBER_PROFILE M
JOIN (SELECT W.MEMBER_ID, W.REVIEW_TEXT, W.REVIEW_DATE
      FROM REST_REVIEW W
      JOIN (SELECT MEMBER_ID, COUNT(MEMBER_ID)
            FROM REST_REVIEW
            GROUP BY 1
            ORDER BY 2 DESC
            LIMIT 1
           ) V
      ON W.MEMBER_ID = V.MEMBER_ID
     ) R
ON M.MEMBER_ID = R.MEMBER_ID
ORDER BY 3, 2