SELECT 
    YEAR(O.SALES_DATE) AS 'YEAR', 
    MONTH(O.SALES_DATE) AS 'MONTH',
    GENDER,
    COUNT(DISTINCT O.USER_ID) AS 'USERS'
FROM ONLINE_SALE O
JOIN (SELECT * FROM USER_INFO
      WHERE GENDER IS NOT NULL
     ) U
ON O.USER_ID = U.USER_ID
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), GENDER
ORDER BY 1, 2, 3