SELECT P.CATEGORY, P.PRICE, P.PRODUCT_NAME
FROM (SELECT *, RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANKING 
      FROM FOOD_PRODUCT
      WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
     ) P
WHERE P.RANKING = 1
ORDER BY 2 DESC