SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS 'FAVORITES' 
    FROM REST_INFO 
    GROUP BY FOOD_TYPE
) I
ON R.FAVORITES = I.FAVORITES AND R.FOOD_TYPE = I.FOOD_TYPE
ORDER BY 1 DESC