SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P
JOIN  (SELECT * FROM APPOINTMENT
       WHERE MCDP_CD = 'CS'
       AND APNT_CNCL_YN = 'N'
       AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
      ) A
ON P.PT_NO = A.PT_NO
JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
ORDER BY A.APNT_YMD